const quizQuestions = [
    {
      question: ' What is JavaScript?',
      options: [ 'JavaScript is a scripting language used to make the website interactive',
         'JavaScript is an assembly language used to make the website interactive',
         'JavaScript is a compiled language used to make the website interactive',
         'None of the mentioned'],
      answer: 'JavaScript is a scripting language used to make the website interactive',
    },
    {
      question: 'Arrays in JavaScript are defined by which of the following statements?',
      options: [' It is an ordered list of values',
        ' It is an ordered list of objects',
         'It is an ordered list of string',
         'It is an ordered list of functions'],
      answer: ' It is an ordered list of values',
    },
    {
      question: 'Which of the following is not javascript data types?',
      options: [ 'Null type',
         'Undefined type',
         'Number type',
         'All of the mentioned'],
      answer: 'All of the mentioned',
    },
    {
      question: 'Why JavaScript Engine is needed?',
      options: ['Both Compiling & Interpreting the JavaScript',
         'Parsing the javascript',
         'Interpreting the JavaScript',
         'Compiling the JavaScript'],
      answer: 'Interpreting the JavaScript',
    },
    {
      question: 'In which HTML element, we put the JavaScript code?',
      options: ['<javascript>...</javascript>',
        '<js>...</js>',
        ' <script>...</script>',
        '<css>...</css>'
      ],
      answer: '<script>...</script>',
    },
    {
      question: 'Which JavaScript method is used to access an HTML element by id?',
      options: ['getElementById()',
       ' getElement(id)',
       ' getElementById(id)',
       ' elementById(id)]',
    ],
      answer: 'getElementById(id)',
    },
    {
      question: 'Which property is used to define the HTML content to an HTML element with a specific id?',
      options: ['innerText',
       'innerContent',
       'elementText',
       'innerHTML',
      ],
      answer: 'innerHTML',
    },
    {
      question: 'Which JavaScript method is used to write HTML output?',
      options: ['document.write()',
        'document.output()',
        'console.log()',
        'document.writeHTML()',],
      answer: 'document.write()',
    },
    {
      question: ' What is the default value of an uninitialized variable?',
      options: ['0',
        'undefined',
        'null',
        'NaN',
        
      ],
      answer: 'undefined',
    },
    {
      question: 'JavaScript arrays are written with _____.',
      options: ['round brackets ()',
        'curly brackets {}',
        'double quotes ""',
        'square brackets []'],
      answer: 'square brackets []',
    },
  ];
  
